### PR TITLE
Add CNAME

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by cllns** [comment]
http://awesome-hanami.org/ 👯 

looks great!

**Comment by davydovanton** [comment]
@cllns yep, but I have some troubles with my DNS service. I think tomorrow we will have new site :)

**Comment by cllns** [comment]
It's working fine for me. Not sure if you mean some other DNS issue though :)

**Comment by davydovanton** [comment]
@cllns yep, I have problem with my provider 😞

**Pull request merged**
