### PR TITLE
Added enterprise app: Loan Application platform

### PR DESCRIPTION
**Pull request by hlegius**
Credita's loan application app. Internally known as "Core" app.

### CODE REVIEW

**Review by davydovanton — APPROVED** [review]
🎉

**Comment by davydovanton** [comment]
I think we need to split our list into `production` and `play` projects in next iteration. WDYT?

**Comment by davydovanton** [comment]
Thanks for contribution 👍

**Comment by hlegius** [comment]
@davydovanton would be good - at least split into open source play/pet projects from the closed ones. Could make readability easier. Thoughts?

**Comment by cllns** [comment]
> I think we need to split our list into production and play projects in next iteration. WDYT?

Good idea 👍

**Comment by davydovanton** [comment]
I think it should be
```
## Projects
### Production
### OSS
### Play/Pet projects
```

**Comment by hlegius** [comment]
Makes sense! It will incentive more people add their projects there.

**Comment by davydovanton** [comment]
did it 👍
@hlegius thanks for help again 👏

**Pull request merged**
